"""Add many-to-many relationships for books, genres, and categories

Revision ID: 8e74ddb60189
Revises: 428aa3fd64cd
Create Date: 2026-05-17 01:03:16.999226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e74ddb60189'
down_revision: Union[str, None] = '428aa3fd64cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_category',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'category_id')
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.drop_constraint('book_author_id_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('favorite_user_id_fkey', 'favorite', type_='foreignkey')
    op.drop_constraint('favorite_book_id_fkey', 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorite', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_book_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    op.create_foreign_key('review_book_id_fkey', 'review', 'book', ['book_id'], ['id'])
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key('favorite_book_id_fkey', 'favorite', 'book', ['book_id'], ['id'])
    op.create_foreign_key('favorite_user_id_fkey', 'favorite', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    op.drop_table('book_genre')
    op.drop_table('book_category')
    # ### end Alembic commands ###
